sudo: false
language: python
python:
  - 2.6
  - 2.7
# - 3.2 dest.write(u'  ') SyntaxError: invalid syntax
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install argparse
  - pip install coverage
  - pip install codeclimate-test-reporter
script:
  - coverage run lld-nfs.py
after_success:
  - codeclimate-test-reporter
